# Generated by Django 4.2.10 on 2024-02-27 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyrecommendation',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='companyrecommendation',
            old_name='contact_page_url',
            new_name='contact_link',
        ),
        migrations.RemoveField(
            model_name='companyrecommendation',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='companyrecommendation',
            name='google_search_query',
        ),
        migrations.AddField(
            model_name='companyrecommendation',
            name='emails',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyrecommendation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
