# Generated by Django 4.2.10 on 2024-02-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0002_rename_name_companyrecommendation_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrecommendation',
            name='emails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
