# Generated by Django 4.2.10 on 2024-02-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0003_alter_companyrecommendation_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrecommendation',
            name='company_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
