# Generated by Django 4.2.10 on 2024-02-27 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0004_alter_companyrecommendation_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrecommendation',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='companyrecommendation',
            name='emails',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
